#!/usr/bin/env python3
"""
build_sitemap.py — regenerate sitemap.xml from the real pages.   Version: V1

Reads every page's <link rel="canonical"> so the sitemap always matches the
canonical URLs. Pages with a "noindex" robots meta (e.g. 404.html) are left out.
Priority is set by folder depth. lastmod is the file's modified date.
Handles up to 50,000 URLs (Google's per-sitemap limit), far above 500 pages.

    python tools/build_sitemap.py
"""
import re
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKIP_DIRS = {"partials", "tools", "templates", "data", ".git", "node_modules", "assets"}
CANON = re.compile(r'<link rel="canonical" href="([^"]+)"')
NOINDEX = re.compile(r'<meta name="robots" content="[^"]*noindex', re.I)
PRIORITY = {"index.html": "1.0", "services/index.html": "0.9", "menus.html": "0.9", "contact.html": "0.8",
            "about.html": "0.7", "gallery.html": "0.6", "privacy.html": "0.2", "terms.html": "0.2"}


def main():
    rows = []
    for page in sorted(ROOT.rglob("*.html")):
        rel = page.relative_to(ROOT).as_posix()
        if rel.split("/")[0] in SKIP_DIRS:
            continue
        text = page.read_text(encoding="utf-8")
        if NOINDEX.search(text):
            continue
        m = CANON.search(text)
        if not m:
            print(f"  ! no canonical, skipped: {rel}")
            continue
        prio = PRIORITY.get(rel, "0.8" if rel.startswith("services/") else "0.6")
        lastmod = date.fromtimestamp(page.stat().st_mtime).isoformat()
        rows.append((prio, m.group(1), lastmod))
    rows.sort(key=lambda r: (-float(r[0]), r[1]))
    body = "\n".join(
        f"  <url>\n    <loc>{loc}</loc>\n    <lastmod>{lm}</lastmod>\n    <priority>{p}</priority>\n  </url>"
        for p, loc, lm in rows)
    xml = ('<?xml version="1.0" encoding="UTF-8"?>\n'
           '<!-- Vellore Catering World sitemap | generated by tools/build_sitemap.py | Version: V1 -->\n'
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + body + "\n</urlset>\n")
    (ROOT / "sitemap.xml").write_text(xml, encoding="utf-8")
    print(f"build_sitemap: {len(rows)} URLs written to sitemap.xml")


if __name__ == "__main__":
    main()
